/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import config.conexion;
import java.awt.Component;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Empresa extends javax.swing.JFrame {

    conexion con = new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;

    public Empresa() {
        initComponents();
        setLocationRelativeTo(null);
        jLblmensaje.setVisible(false);
        persona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTxtcod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtncerrarsesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelinfo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTxtID = new javax.swing.JTextField();
        jTxtnom = new javax.swing.JTextField();
        jTxtfecha = new javax.swing.JTextField();
        jTxtpeso = new javax.swing.JTextField();
        jTxtestado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtcodigo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jBtnborraresp = new javax.swing.JButton();
        jBtnagregar = new javax.swing.JButton();
        jBtnconsultar = new javax.swing.JButton();
        jBtneliminar = new javax.swing.JButton();
        jBtnmod = new javax.swing.JButton();
        jBtnver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jBtnAdministrar = new javax.swing.JButton();
        jLblmensaje = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Estado");

        jButton6.setText("jButton6");

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Codigo");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logaa.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jBtncerrarsesion.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.JPG"))); // NOI18N
        jBtncerrarsesion.setText("Cerrar sesion");
        jBtncerrarsesion.setActionCommand("");
        jBtncerrarsesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtncerrarsesionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER: ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelinfo.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Fabricacion");

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Peso Gr");

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado B/M");

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Codigo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jTxtpeso))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jTxtestado))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jTxtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jBtnborraresp.setBackground(new java.awt.Color(153, 153, 153));
        jBtnborraresp.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtnborraresp.setText("Borrar Espacios");
        jBtnborraresp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnborraresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnborrarespActionPerformed(evt);
            }
        });

        jBtnagregar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtnagregar.setText("Agregar");
        jBtnagregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnagregarActionPerformed(evt);
            }
        });

        jBtnconsultar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtnconsultar.setText("Consultar");
        jBtnconsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnconsultarActionPerformed(evt);
            }
        });

        jBtneliminar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtneliminar.setText("Eliminar");
        jBtneliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtneliminarActionPerformed(evt);
            }
        });

        jBtnmod.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtnmod.setText("Modificar");
        jBtnmod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnmodActionPerformed(evt);
            }
        });

        jBtnver.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtnver.setText("Ver Todo");
        jBtnver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnverActionPerformed(evt);
            }
        });

        TablaDatos.setBackground(new java.awt.Color(204, 204, 204));
        TablaDatos.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Fecha de Fabricacion", "Peso Gr", "Estado", "Codigo"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);
        if (TablaDatos.getColumnModel().getColumnCount() > 0) {
            TablaDatos.getColumnModel().getColumn(0).setMaxWidth(50);
            TablaDatos.getColumnModel().getColumn(3).setMaxWidth(80);
            TablaDatos.getColumnModel().getColumn(4).setMaxWidth(60);
            TablaDatos.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanelinfoLayout = new javax.swing.GroupLayout(jPanelinfo);
        jPanelinfo.setLayout(jPanelinfoLayout);
        jPanelinfoLayout.setHorizontalGroup(
            jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfoLayout.createSequentialGroup()
                        .addComponent(jBtnborraresp)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfoLayout.createSequentialGroup()
                        .addGroup(jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelinfoLayout.createSequentialGroup()
                                .addComponent(jBtnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jBtnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jBtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jBtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(jBtnver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanelinfoLayout.setVerticalGroup(
            jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnborraresp)
                .addGap(18, 18, 18)
                .addGroup(jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jBtnAdministrar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jBtnAdministrar.setText("Administrar");
        jBtnAdministrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdministrarActionPerformed(evt);
            }
        });

        jLblmensaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblmensaje.setForeground(new java.awt.Color(153, 0, 0));
        jLblmensaje.setText("NO TIENES AUTORIZACION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLblmensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBtncerrarsesion)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblmensaje)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtncerrarsesion)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtncerrarsesionActionPerformed
        this.setVisible(false);
        Login f1 = new Login();
        f1.setVisible(true);

    }//GEN-LAST:event_jBtncerrarsesionActionPerformed
    /*--------------------------------------------------------------*/
    
    //Variable jj que recibe el string 'u' , la variable recibe el documento de quien ha ingresado
    static String jj;
    void user(String u) {
        jj=u;
    }
    //funcion que realiza la consulta con el documento(jj) y muestra el nombre de quien ha ingresado
    void persona(){
        String sql="Select NombreCompleto,Autorizacion,Administrador from usuarios where documento=" + jj;
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            String nm=null;
            String aut=null;
            String adm=null;
            //if para almacenar en variables las consultas del sql
            if(rs.next()){
                nm=rs.getString(1);
                aut=rs.getString(2);
                adm=rs.getString(3);
            }
            //set para mostrar en el jlabel el nombre de la persona que ingreso
            jLabel6.setText(nm);
            //---------------------------------------------------------------------------//
            //la persona que no sea administrador no se mostrara el boton de administrar
            //el boton administrar modifica que persona tiene acceso a modificar informacion de la empresa
            String N="not";
            if(N.equals(adm)){
                jBtnAdministrar.setVisible(false);
            }
            //----------------------------------------------------------------------------//
            //la persona que no tenga acceso se bloquearan las funciones y mostrara mensaje de alerta
            //El mensaje estara siempre desactivado en la funcion principal Empresa()
            String D="D";
            if(D.equals(aut)){
                
                for (Component component : jPanelinfo.getComponents()) {
                    component.setEnabled(false); 
                }
                jLblmensaje.setVisible(true);
                
            }
            //----------------------------------------------------------------------------//
        }catch (Exception e){
            System.out.println(e);
        }
        
    }
    
    /*--------------------------------------------------------------*/

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO a dd your handling code here:
        //usando();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnconsultarActionPerformed
        consultar();
    }//GEN-LAST:event_jBtnconsultarActionPerformed

    private void jBtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnagregarActionPerformed
        agregar();
    }//GEN-LAST:event_jBtnagregarActionPerformed

    private void jBtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtneliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_jBtneliminarActionPerformed

    private void jBtnborrarespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnborrarespActionPerformed
        borrarespacios();
    }//GEN-LAST:event_jBtnborrarespActionPerformed

    private void jBtnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnverActionPerformed
        vertodo();
    }//GEN-LAST:event_jBtnverActionPerformed
    
    //Funcion para que al momento de dar click en la tabla se muestre la informacion en los jtext
    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        int fila = TablaDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Usuario no seleccionado");
        } else {
            id = Integer.parseInt((String) TablaDatos.getValueAt(fila, 0).toString());
            String nom = (String) TablaDatos.getValueAt(fila, 1);
            String date = (String) TablaDatos.getValueAt(fila, 2);
            String peso = (String) TablaDatos.getValueAt(fila, 3);
            String estado = (String) TablaDatos.getValueAt(fila, 4);
            String codigo = (String) TablaDatos.getValueAt(fila, 5);
            jTxtID.setText("" + id);
            jTxtnom.setText(nom);
            jTxtfecha.setText(date);
            jTxtpeso.setText(peso);
            jTxtestado.setText(estado);
            jTxtcodigo.setText(codigo);
        }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void jBtnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnmodActionPerformed
        modificar();
    }//GEN-LAST:event_jBtnmodActionPerformed
    
    //jbtn para administrar el acceso de los usuarios
    private void jBtnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdministrarActionPerformed
        Administrar adm=new Administrar();
        adm.setVisible(true);
        
        
    }//GEN-LAST:event_jBtnAdministrarActionPerformed

//--------------------------------------------------------------------------------------------------------/ /   

    void borrarespacios() {
        //Para que al oprimir el boton se borren los jtext
        jTxtID.setText("");
        jTxtnom.setText("");
        jTxtfecha.setText("");
        jTxtpeso.setText("");
        jTxtestado.setText("");
        jTxtcodigo.setText("");
    }

    void agregar() {
        //Se traen las variables
        String nom = jTxtnom.getText().trim();
        String date = jTxtfecha.getText().trim();
        String peso = jTxtpeso.getText().trim();
        String estado = jTxtestado.getText().trim();
        String codigo = jTxtcodigo.getText().trim();
        //Sql a ejecutar
        String sql2 = "Select Codigo from inventario where Codigo=" + codigo;
        String sql = "Insert into inventario (Nombre,FechaDeFabricacion,PesoGr,Estado,Codigo)value('" + nom + "','" + date + "','" + peso + "','" + estado + "','" + codigo + "')";
        //if para que ninguno de los espacios quede vacio
        if (nom.equals("") || date.equals("") || peso.equals("") || estado.equals("") || codigo.equals("")) {
            JOptionPane.showMessageDialog(null, "Espacios vacios", "Mensaje", HEIGHT);
        } else {

            try {
                cn = con.getConnection();
                st = cn.createStatement();
                rs = st.executeQuery(sql2);
                String ver = null;
                //if para almacenar en variable la consulta de sql2
                if (rs.next()) {
                    ver = rs.getString(1);
                }
                //if para que el objeto a agregar no tenga el mismo codigo
                if (codigo.equals(ver)) {
                    JOptionPane.showMessageDialog(null, "Este objeto ya existe", "Mensaje", HEIGHT);
                } else {
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Objeto Agregado");
                }

            } catch (Exception e) {
                System.out.println(e);
            }

        }

    }

    void consultar() {

        //Se traen las variables
        String nom = jTxtnom.getText().trim();
        String codigo = jTxtcodigo.getText().trim();

        //Sql a ejecutar
        String sql = "SELECT * from inventario where Codigo=" + codigo;
        String sql2 = "SELECT * from inventario where Nombre='" + nom + "'";
        //Solo se puede realizar la consulta con codigo y nombre

        if ((codigo.equals("")) && (nom.equals(""))) { //if para que los jtext de codigo y nombre no esten vacios
            JOptionPane.showMessageDialog(null, "Se realizan consultas solo con el nombre o el codigo");
        } else if (nom.equals("")) {   //if para que si nombre este vacio y se ejecute con codigo
            try {
                limpiartabla();
                cn = con.getConnection();
                st = cn.createStatement();

                rs = st.executeQuery(sql);

                Object[] registros = new Object[6];
                modelo = (DefaultTableModel) TablaDatos.getModel();
                while (rs.next()) {
                    registros[0] = rs.getInt("ID");
                    registros[1] = rs.getString("Nombre");
                    registros[2] = rs.getString("FechaDeFabricacion");
                    registros[3] = rs.getString("PesoGr");
                    registros[4] = rs.getString("Estado");
                    registros[5] = rs.getString("Codigo");
                    modelo.addRow(registros);
                }
                TablaDatos.setModel(modelo);
            } catch (Exception e) {
                System.out.println("-----");
                System.out.println(e);
                System.out.println("-----");
            }

        } else if (codigo.equals("")) {    //if para que si codigo este vacio y se ejecute con nombre
            try {
                limpiartabla();
                cn = con.getConnection();
                st = cn.createStatement();

                rs = st.executeQuery(sql2);

                Object[] registro = new Object[6];
                modelo = (DefaultTableModel) TablaDatos.getModel();
                while (rs.next()) {
                    registro[0] = rs.getInt("ID");
                    registro[1] = rs.getString("Nombre");
                    registro[2] = rs.getString("FechaDeFabricacion");
                    registro[3] = rs.getString("PesoGr");
                    registro[4] = rs.getString("Estado");
                    registro[5] = rs.getString("Codigo");
                    modelo.addRow(registro);
                }
                TablaDatos.setModel(modelo);
            } catch (Exception e) {
                System.out.println("=====");
                System.out.println(e);
                System.out.println("=====");
            }
        } else {    //if para que si ambos esten llenos se ejecute con codigo
            try {
                limpiartabla();
                cn = con.getConnection();
                st = cn.createStatement();

                rs = st.executeQuery(sql);

                Object[] registro = new Object[6];
                modelo = (DefaultTableModel) TablaDatos.getModel();
                while (rs.next()) {
                    registro[0] = rs.getInt("ID");
                    registro[1] = rs.getString("Nombre");
                    registro[2] = rs.getString("FechaDeFabricacion");
                    registro[3] = rs.getString("PesoGr");
                    registro[4] = rs.getString("Estado");
                    registro[5] = rs.getString("Codigo");
                    modelo.addRow(registro);
                }
                TablaDatos.setModel(modelo);
            } catch (Exception e) {
                System.out.println("=====");
                System.out.println(e);
                System.out.println("=====");
            }
        }

    }

    void modificar() {
        //Se traen las variables
        String nom = jTxtnom.getText().trim();
        String date = jTxtfecha.getText().trim();
        String peso = jTxtpeso.getText().trim();
        String estado = jTxtestado.getText().trim();
        String codigo = jTxtcodigo.getText().trim();
        //sql a ejecutar
        String sql = "update inventario set Nombre=('" + nom + "'), FechadeFabricacion=('" + date + "'), PesoGr=('" + peso + "'), Estado=('" + estado + "'), Codigo=('" + codigo + "') where ID=" + id;
        String sql2 = "Select Codigo from inventario where Codigo=" + codigo;

        try {
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            String cod = null;
            //cod para verificar la existencia del objeto que se valla a modificar
            if (rs.next()) {
                cod = rs.getString(1);
            }
            //if para que ninguno de los espacios quede vacios
            if (nom.equals("") || date.equals("") || peso.equals("") || estado.equals("") || codigo.equals("")) {
                JOptionPane.showMessageDialog(null, "Espacios vacios");

            } else if (codigo.equals(cod)) { //if para saber si el objeto exista con la variable codigo y actualizar
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Objeto actualizado");
                consultar();
            } else {  //Si no es porque el objeto no existe
                JOptionPane.showMessageDialog(null, "Este objeto no existe");
            }

        } catch (Exception e) {

        }

    }

    void vertodo() {
        //Sql a ejecutar
        String sql = "SELECT * from inventario";
        try {
            limpiartabla();
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            //Se crea objeto para almacenar en la tabla
            Object[] registros = new Object[6];
            modelo = (DefaultTableModel) TablaDatos.getModel();
            while (rs.next()) {
                registros[0] = rs.getInt("ID");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("FechaDeFabricacion");
                registros[3] = rs.getString("PesoGr");
                registros[4] = rs.getString("Estado");
                registros[5] = rs.getString("Codigo");
                modelo.addRow(registros);
            }
            TablaDatos.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void eliminar() {
        //Sql a ejecutar con id que se almacena con el TablaDatosMouseClicked
        String sql = "delete from inventario where ID=" + id;
        //Se almacena la fila seleccionada en la tabla
        int filaseleccionado = TablaDatos.getSelectedRow();
        //if para que se seleccione la fila a eliminar
        if (filaseleccionado == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar fila");
        } else {
            int Op = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar este objeto?");
            if (Op == 0) { //if para confirmar que se desea eliminar el objeto con el JOptionPane Op
                try {
                    cn = con.getConnection();
                    st = cn.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Objeto eliminado");
                    limpiartabla();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }

        }
    }

    //Funcion para limpiar tabla y que no se repitan la misma informacion en la tabla con otras funciones
    void limpiartabla() {
        for (int i = 0; i < TablaDatos.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;

        }
    }

//--------------------------------------------------------------------------------------------------------/ /   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton jBtnAdministrar;
    private javax.swing.JButton jBtnagregar;
    public javax.swing.JButton jBtnborraresp;
    private javax.swing.JButton jBtncerrarsesion;
    private javax.swing.JButton jBtnconsultar;
    private javax.swing.JButton jBtneliminar;
    private javax.swing.JButton jBtnmod;
    private javax.swing.JButton jBtnver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblmensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelinfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtcod;
    private javax.swing.JTextField jTxtcodigo;
    private javax.swing.JTextField jTxtestado;
    private javax.swing.JTextField jTxtfecha;
    private javax.swing.JTextField jTxtnom;
    private javax.swing.JTextField jTxtpeso;
    // End of variables declaration//GEN-END:variables

}
